import type { Metadata } from "next";
import "./globals.css";
import { satoshi, monumentExtended } from "./_fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${monumentExtended.variable} font-sans bg-black text-white`}>{children}</body>
    </html>
  );
}
